
name: Deploy to xserver.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: rsync -avz -e 'ssh -p 10022' --delete build/ hexmiu@sv14058.xserver.jp:~/masa-sumimoto.com/public_html/suuumin-sampler-ui.masa-sumimoto.com
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}


# name: Build and deploy

# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '16'

#     - name: Install Dependencies
#       run: npm install

#     - name: Build
#       run: npm run build --if-present

#     - name: Deploy to Server via SSH
#       uses: easingthemes/ssh-deploy@v3
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
#         ARGS: "-rlgoDzvc -i --delete"
#         SOURCE: "dist/"
#         REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
#         REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
#         TARGET: ${{ secrets.DEPLOY_DIR }}
#         REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
#         EXCLUDE: "/dist/, /node_modules/"

    # - name: new Deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DEPLOY_SERVER }}
    #     username: ${{ secrets.DEPLOY_USERNAME }}
    #     port: ${{ secrets.DEPLOY_PORT }}
    #     key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY_2 }}
    #     # passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
    #     script: |
    #       cd ${{ secrets.DEPLOY_DIR }}
    #       git pull origin main




# FTP
#
# on:
#   push:
#     branches:
#       - main
# name: Deploy
# jobs:
#   FTP-Deploy-Action:
#     name: FTP-Deploy-Action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: FTP-Deploy-Action
#         uses: SamKirkland/FTP-Deploy-Action@2.0.0
#         env:
#           FTP_SERVER: ${{ secrets.FTP_HOST }}
#           FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#           LOCAL_DIR: ./tst/
#           REMOTE_DIR: ${{ secrets.DEPLOY_DIR }}